# Generated by Django 4.2 on 2023-05-25 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saved',
            name='body',
        ),
    ]
